name: Build Kali ARM Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Verify kali-arm exists
        run: |
          [ -d "kali-arm" ] || { echo "Error: kali-arm directory missing! Run update workflow first."; exit 1; }

      - name: Install build dependencies
        run: |
          sudo apt-get update
          # Install both systemd-container and kali's specific dependencies
          sudo apt-get install -y systemd-container qemu-user-static
          cd kali-arm
          sudo ./common.d/build_deps.sh
          cd ..

      - name: Set terminal environment
        run: |
          echo 'export TERM=xterm' >> ~/.bashrc

      - name: Build images
        run: |
          cd kali-arm
          export TERM=xterm
          for script in raspberry-pi-64-bit.sh raspberry-pi-zero-2-w.sh; do
            chmod +x $script
            echo "Building with $script..."
            sudo --preserve-env=TERM ./$script --desktop=none -s
          done

      - name: Publish images
        run: |
          mkdir -p images
          sudo chown -R $USER:$USER kali-arm/images/
          mv kali-arm/images/*.img images/
          
          echo "Build date: $(date)" > images/build-info.txt
          echo "Commit: $(git rev-parse HEAD)" >> images/build-info.txt
          echo "Dependencies:" >> images/build-info.txt
          dpkg -l systemd-container qemu-user-static >> images/build-info.txt
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add images/
          git commit -m "Add built images from $(date +%Y-%m-%d)"
          git push

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kali-images
          path: images/
          retention-days: 3
