name: Build Kali ARM Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: ["raspberry-pi-64-bit.sh", "raspberry-pi-zero-2-w.sh"]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Verify kali-arm exists
        run: |
          [ -d "kali-arm" ] || { echo "Error: kali-arm directory missing! Run update workflow first."; exit 1; }

      - name: Cache system dependencies
        uses: actions/cache@v3
        id: sysdep-cache
        with:
          path: |
            /var/cache/apt
            /var/lib/apt
          key: ${{ runner.os }}-sysdeps-${{ hashFiles('kali-arm/common.d/build_deps.sh') }}
          restore-keys: |
            ${{ runner.os }}-sysdeps-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            systemd-container \
            qemu-user-static \
            debootstrap \
            git \
            curl
          sudo apt-get clean

      - name: Cache Kali build dependencies
        uses: actions/cache@v3
        id: kali-dep-cache
        with:
          path: kali-arm/deps
          key: ${{ runner.os }}-kalideps-${{ hashFiles('kali-arm/common.d/build_deps.sh') }}
          restore-keys: |
            ${{ runner.os }}-kalideps-

      - name: Install Kali build dependencies
        run: |
          cd kali-arm
          mkdir -p deps
          sudo ./common.d/build_deps.sh
          cd ..

      - name: Build image
        run: |
          cd kali-arm
          export TERM=xterm
          chmod +x ${{ matrix.script }}
          sudo --preserve-env=TERM ./${{ matrix.script }} --desktop=none -s
          
          # Move and rename the built image
          mkdir -p ../images/
          img_file=$(ls images/*.img | head -n 1)
          new_name="$(basename "$img_file" .img)-$(date +%Y%m%d).img"
          mv "$img_file" "../images/$new_name"

      - name: Publish images
        if: matrix.script == 'raspberry-pi-zero-2-w.sh' # Only run once
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add images/
          git commit -m "Add built images from $(date +%Y-%m-%d)"
          git push

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.script }}-image
          path: images/
          retention-days: 3
