name: Kali ARM Build Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize subtree
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          if ! git remote | grep -q kali-arm; then
            git remote add kali-arm https://gitlab.com/kalilinux/build-scripts/kali-arm.git
          fi
          
          git fetch kali-arm main
          
          if [ ! -d "kali-arm" ]; then
            git merge --allow-unrelated-histories -s ours --no-commit kali-arm/main
            git read-tree --prefix=kali-arm/ -u kali-arm/main
            git commit -m "Add Kali ARM subtree"
          else
            git subtree pull --prefix=kali-arm kali-arm main --squash -m "Update Kali ARM subtree"
          fi

      - name: Clone NetFang repo
        run: |
          git clone https://github.com/SpotlightForBugs/NetFang NetFang-repo
          [ -f NetFang-repo/install.sh ] || { echo "Error: install.sh missing!"; exit 1; }

      - name: Configure Build
        run: |
          cd kali-arm
          
          find . -maxdepth 1 -type f -name "*.sh" \
            ! -name "raspberry-pi-64-bit.sh" \
            ! -name "raspberry-pi-zero-2-w.sh" \
            -delete
          
          mkdir -p netfang-files/DEBIAN netfang-files/home/kali/NetFang
          cp -r ../NetFang-repo/* netfang-files/home/kali/NetFang/
          
          cat > netfang-files/DEBIAN/control <<EOF
          Package: netfang-files
          Version: 1.0
          Architecture: all
          Maintainer: Your Name <your@email.com>
          Description: NetFang setup files
          EOF
          
          cat > netfang-files/DEBIAN/postinst <<'EOF'
          #!/bin/sh
          set -e
          chown -R kali:kali /home/kali/NetFang
          chmod +x /home/kali/NetFang/install.sh
          echo '[ -x ~/NetFang/install.sh ] && ~/NetFang/install.sh' >> /home/kali/.bashrc
          EOF
          chmod 755 netfang-files/DEBIAN/postinst
          
          sudo apt-get update && sudo apt-get install -y dpkg-dev
          dpkg-deb --build netfang-files
          
          cat > builder.txt <<EOF
          hostname="NetFang"
          nameserver="1.1.1.1"
          image_name="NetFang-$(date +%Y)-W$(date +%U)-\${hw_model}-\${variant}"
          custom_packages="./netfang-files.deb"
          packages="netfang-files"
          EOF

          git add .
          git commit -m "Configure NetFang build" || echo "No changes to commit"
          git push

  build:
    needs: configure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: ["raspberry-pi-64-bit.sh", "raspberry-pi-zero-2-w.sh"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Image
        run: |
          cd kali-arm
          chmod +x ${{ matrix.script }}
          ./${{ matrix.script }} --desktop=none -s
          
      - name: Publish Images to Repo Root
        run: |
          # Move images to root
          mkdir -p ../images/
          mv kali-arm/images/*.img ../images/
          
          # Commit and push
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add images/
          git commit -m "Add latest built images"
          git push

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.script }}-image
          path: images/
