name: Build Kali ARM Images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create directory
        run: mkdir -p kali-arm

      - name: Check directory existence
        run: |
          [ -d "kali-arm" ] || { echo "Error: kali-arm directory missing!"; exit 1; }

      - name: Change to directory and run script
        run: |
          cd kali-arm
          export TERM=xterm
          chmod +x raspberry-pi-zero-2-w.sh
          sudo --preserve-env=TERM ./raspberry-pi-zero-2-w.sh --desktop=none -s || echo "Build failed, continuing for artifact collection"
