name: Build Kali ARM Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - script: "raspberry-pi-64-bit.sh"
            runner: "ubuntu-24.04-arm"
            arch: "arm64"
          - script: "raspberry-pi-zero-2-w.sh" 
            runner: "ubuntu-22.04-arm"
            arch: "armhf"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Verify kali-arm exists
        run: |
          [ -d "kali-arm" ] || { echo "Error: kali-arm directory missing!"; exit 1; }

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            systemd-container \
            debootstrap \
            kpartx \
            parted \
            udev \
            dosfstools \
            rsync \
            xz-utils
          cd kali-arm
          sudo ./common.d/build_deps.sh
          cd ..

      - name: Build image
        run: |
          cd kali-arm
          export TERM=xterm
          chmod +x ${{ matrix.script }}
          sudo --preserve-env=TERM ./${{ matrix.script }} --desktop=none -s

      - name: Handle built images
        run: |
          cd kali-arm/images
          
          # Find and process the built image
          img_file=$(ls -t *.img* | head -n 1)
          [[ -z "$img_file" ]] && { echo "No image file found!"; exit 1; }
          
          # Decompress if needed
          if [[ "$img_file" == *.xz ]]; then
            echo "Decompressing $img_file..."
            unxz "$img_file"
            img_file="${img_file%.xz}"
          fi
          
          # Move and checksum
          mkdir -p ../../images/
          mv "$img_file" "../../images/${img_file%.img}-${{ matrix.arch }}.img"
          cd ../../images/
          sha256sum "${img_file%.img}-${{ matrix.arch }}.img" > "${img_file%.img}-${{ matrix.arch }}.img.sha256"

      - name: Publish images
        if: matrix.script == 'raspberry-pi-zero-2-w.sh'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add images/
          git commit -m "Add ARM-built images from $(date +%Y-%m-%d)"
          git push

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.script }}-image-${{ matrix.arch }}
          path: images/
          retention-days: 3
