name: Update Kali ARM Build Scripts

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete existing kali-arm
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          [ -d "kali-arm" ] && git rm -r kali-arm
          git commit -m "Remove old kali-arm" || echo "Nothing to remove"

      - name: Clone fresh copy
        run: |
          git clone --depth 1 https://gitlab.com/kalilinux/build-scripts/kali-arm.git kali-arm-temp
          rm -rf kali-arm-temp/.git
          mv kali-arm-temp kali-arm
          git add kali-arm
          git commit -m "Update kali-arm to latest version"
          git push
