name: Update and Configure Kali ARM Subtree

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  configure-subtree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Subtree
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add kali-arm https://gitlab.com/kalilinux/build-scripts/kali-arm.git || true
          git fetch kali-arm main
          git subtree pull --prefix=kali-arm kali-arm main --squash -m "chore: Update Kali ARM subtree"

      - name: Clean and configure
        run: |
          cd kali-arm
          
          # Remove unwanted files
          rm -f README.md
          find . -maxdepth 1 -type f -name "*.sh" ! -name "raspberry-pi-zero-2-w.sh" -delete
          
          # Create builder.txt
          cat > builder.txt <<EOF
          hostname="NetFang"
          nameserver="1.1.1.1"
          image_name="NetFang-$(date +%Y)-W$(date +%U)-\${hw_model}-\${variant}"
          EOF
          
          cd ..
          git add kali-arm
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: Update kali-arm configuration"
            git push
          fi
